FROM centos:7
MAINTAINER Mark Bonano, mbonano@scholastic.com

# Upgrading system
RUN yum -y upgrade
RUN yum -y install wget

# Download Oracle Java 8 Archive
RUN wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u101-b13/jdk-8u101-linux-x64.tar.gz" -O /opt/jdk-8u101-linux-x64.tar.gz
RUN tar xzf /opt/jdk-8u101-linux-x64.tar.gz -C /opt

# Install Oracle Java 8 with alternatives
RUN alternatives --install /usr/bin/java java /opt/jdk1.8.0_101/bin/java 2
RUN alternatives --install /usr/bin/jar jar /opt/jdk1.8.0_101/bin/jar 2
RUN alternatives --install /usr/bin/javac javac /opt/jdk1.8.0_101/bin/javac 2
RUN alternatives --set jar /opt/jdk1.8.0_101/bin/jar
RUN alternatives --set javac /opt/jdk1.8.0_101/bin/javac

# Configure common environment variables
ENV JAVA_HOME /opt/jdk1.8.0_101
ENV JRE_HOME /opt/jdk1.8.0_101/jre
ENV PATH $PATH:/opt/jdk1.8.0_101/bin:/opt/jdk1.8.0_101/jre/bin

# install maven
RUN wget -O /opt/apache-maven-3.3.9-bin.tar.gz http://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
RUN tar -xzvf /opt/apache-maven-3.3.9-bin.tar.gz -C /opt
ENV PATH $PATH:/opt/apache-maven-3.3.9/bin

# set application volue
VOLUME /opt/app

# set application directory as working directory
WORKDIR /opt/app

# Define entrypoint
ENTRYPOINT ["mvn", "spring-boot:run"]
