version: '2'
services:
  app:
    image: "${image_name}_DEV"
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # map source root dir to app root dir
      - .:/opt/app
      # map maven repo in order to cache maven dependencies
      - ./.m2:/root/.m2
    ports:
      - "9011:8080"

  app-image:
    image: "${image_name}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        compiled_binary_path: "${compiled_binary_path}"


